# Generated by Django 2.2.4 on 2020-01-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seen', '0002_auto_20200115_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter_seen',
            name='computer_info',
            field=models.CharField(blank=True, max_length=508, null=True),
        ),
    ]
