# Generated by Django 2.2.4 on 2020-01-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seen', '0003_counter_seen_computer_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter_seen',
            name='computer_info',
        ),
    ]
