# Generated by Django 2.2.4 on 2020-01-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seen', '0004_remove_counter_seen_computer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter_seen',
            name='path',
            field=models.CharField(max_length=504),
        ),
    ]
