# Generated by Django 2.2.4 on 2019-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='news-pic/', verbose_name='تصویر '),
        ),
    ]
