# Generated by Django 2.2.4 on 2019-09-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190919_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.ImageField(blank=True, default='news-pic/default.png', null=True, upload_to='news-pic/', verbose_name='تصویر '),
        ),
    ]
