# Generated by Django 2.2.4 on 2019-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190919_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Public', 'public')], default='Draft', max_length=32, verbose_name='وضعیت '),
        ),
    ]
