# Generated by Django 2.2.4 on 2019-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_new_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Publish', 'public')], default='Draft', max_length=32, verbose_name='وضعیت '),
        ),
    ]
