# Generated by Django 2.2.4 on 2019-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_send_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Read', 'خوانده شد'), ('UnRead', 'خوانده نشده')], default='UnReade', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Send_Message',
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Publish', 'publish')], default='Draft', max_length=32, verbose_name='وضعیت '),
        ),
    ]
