# Generated by Django 2.2.4 on 2019-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20191227_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='national_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
