# Generated by Django 2.2.4 on 2020-01-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20191231_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='driver_id',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Publish', 'publish')], default='Draft', max_length=32, verbose_name='وضعیت '),
        ),
    ]
