# Generated by Django 2.2.4 on 2020-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200107_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='driver_id',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Publish', 'publish'), ('Draft', 'draft')], default='Draft', max_length=32, verbose_name='وضعیت '),
        ),
    ]
