# Generated by Django 2.2.4 on 2019-09-16 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='After_Death_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع ')),
                ('total_price', models.IntegerField(default=0, verbose_name='کل هزینه ')),
            ],
            options={
                'verbose_name': 'خدمات پس از مرگ',
                'verbose_name_plural': 'خدمات پس از مرگ',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=64, verbose_name='نام خانوادگی ')),
                ('national_number', models.CharField(max_length=11, unique=True, verbose_name='شماره ملی ')),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره شناسنامه ')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس ')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ')),
            ],
            options={
                'verbose_name': 'خریدار',
                'verbose_name_plural': 'خریدار',
            },
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deceased_type', models.CharField(choices=[('_', '_')], default='_', max_length=32, verbose_name='نوع جنازه ')),
                ('deceased_status', models.CharField(choices=[('_', '_')], default='_', max_length=32, verbose_name='وضعیت جنازه ')),
                ('first_name', models.CharField(max_length=64, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=64, verbose_name='نام خانوادگی ')),
                ('national_number', models.CharField(max_length=11, verbose_name='شماره ملی ')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد ')),
                ('sex', models.CharField(choices=[('MALE', 'مرد'), ('FEMALE', 'زن'), ('UNKNOWN', 'ناشناخته')], default='UNKNOWN', max_length=32, verbose_name='جنسیت ')),
                ('fa_name', models.CharField(max_length=64, verbose_name='نام پدر ')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='زندگی نامه ')),
                ('mo_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام مادر ')),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره شناسنامه ')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور ')),
                ('place_of_birth', models.CharField(blank=True, max_length=32, null=True, verbose_name='محل تولد ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس ')),
                ('slug', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'افراد فوت شده',
                'verbose_name_plural': 'افراد فوت شده',
            },
        ),
        migrations.CreateModel(
            name='Madah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='نام و نام خانوادگی مداح ')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس ')),
                ('grade', models.CharField(choices=[('Number One', 'درجه یک'), ('Number Two', 'درجه دو'), ('Number Three', 'درجه سه')], default=None, max_length=64, verbose_name='سطح ')),
                ('price', models.IntegerField(verbose_name='هزینه ')),
            ],
            options={
                'verbose_name': 'مداحان',
                'verbose_name_plural': 'مداحان',
            },
        ),
        migrations.CreateModel(
            name='Marasem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='نام ')),
                ('big_table', models.IntegerField(verbose_name='میز بزرگ ')),
                ('echo', models.IntegerField(verbose_name='اکو ')),
                ('panel', models.IntegerField(verbose_name='تابلو ')),
                ('tent', models.IntegerField(verbose_name='چادر با پرده دو طرفه ')),
                ('chair', models.IntegerField(verbose_name='صندلی ')),
                ('carpet', models.IntegerField(verbose_name='فرش ')),
                ('eating_table', models.IntegerField(verbose_name='میز غذا خوری ')),
                ('price', models.IntegerField(verbose_name='هزینه ')),
            ],
            options={
                'verbose_name': 'مجالس',
                'verbose_name_plural': 'مجالس',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام ')),
                ('price', models.IntegerField(verbose_name='هزینه ')),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='کد قبر ')),
                ('longitude', models.CharField(max_length=255, verbose_name='طول جغرافیایی ')),
                ('latitude', models.CharField(max_length=255, verbose_name='عرض جغرافیایی ')),
                ('price', models.CharField(blank=True, max_length=8, null=True, verbose_name='قیمت ')),
                ('ghete', models.CharField(max_length=4, verbose_name='قطعه ')),
                ('radif', models.CharField(max_length=4, verbose_name='ردیف ')),
                ('block', models.CharField(max_length=4, verbose_name='بلوک ')),
                ('number', models.CharField(max_length=4, verbose_name='شماره ')),
                ('floor', models.CharField(choices=[('Normal', 'عادی'), ('OneFloor', 'طبقه یک'), ('TwoFloor', 'طبقه دو')], default='Normal', max_length=12, verbose_name='طبقه ')),
                ('status', models.CharField(choices=[('Pre_sell', 'پیش فروش شده'), ('Municipal', 'شهرداری'), ('Sold', 'فروخته شده')], default='Municipal', max_length=32, verbose_name='وضعیت قبر ')),
                ('type', models.CharField(choices=[('Normal', 'عادی'), ('Celebrities', 'مشاهیر')], default='normal', max_length=32, verbose_name='نوع قبر ')),
            ],
            options={
                'verbose_name': 'قبرها',
                'verbose_name_plural': 'قبرها',
                'unique_together': {('ghete', 'radif', 'block', 'number', 'floor'), ('code', 'ghete', 'radif', 'block', 'number', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='Reader_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع ')),
                ('total_price', models.IntegerField(default=0, verbose_name='هزینه ')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی ')),
                ('madah_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='site_panel.Madah', verbose_name='مداح ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='سفارش دهنده ')),
            ],
            options={
                'verbose_name': 'خدمات مداحان',
                'verbose_name_plural': 'خدمات مداحان',
            },
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=64, verbose_name='نام خانوادگی ')),
                ('national_number', models.CharField(max_length=11, unique=True, verbose_name='شماره ملی ')),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره شناسنامه ')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس ')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ')),
            ],
            options={
                'verbose_name': 'معرف',
                'verbose_name_plural': 'معرف',
            },
        ),
        migrations.CreateModel(
            name='Place_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='شماره سند ')),
                ('payment_status', models.CharField(choices=[('NOT_PAID', 'تسویه نشده'), ('PAID', 'تسویه شد')], default='NOT_PAID', max_length=32, verbose_name='وضعیت پرداخت ')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='خریدار ')),
                ('deceased_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی مربوطه ')),
                ('place_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Place', verbose_name='قبر ')),
            ],
            options={
                'verbose_name': 'سفارش قبر',
                'verbose_name_plural': 'سفارش قبر',
            },
        ),
        migrations.CreateModel(
            name='Memorial_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع ')),
                ('total_price', models.IntegerField(default=0, verbose_name='کل هزینه ')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی ')),
                ('marasem_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='site_panel.Marasem', verbose_name='مجلس ')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='سفارش دهنده ')),
            ],
            options={
                'verbose_name': 'خدمات مجالس',
                'verbose_name_plural': 'خدمات مجالس',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.CharField(max_length=32, unique=True, verbose_name='شماره مجوز ')),
                ('license_status', models.CharField(choices=[('WAITING', 'درحال بررسی'), ('CONFIRMED', 'تایید شده')], default='WAITING', max_length=32, verbose_name='وضعیت مجوز ')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='license-pic/')),
                ('move_status', models.CharField(choices=[('SEND-OUT', 'اعزامی'), ('FERDOS-REZA', 'باغ فردوس')], default='FERDOS-REZA', max_length=32, verbose_name='وضعیت انتقال ')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی ')),
                ('place_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Place', verbose_name='قبر مربوطه ')),
            ],
            options={
                'verbose_name': 'مجوز دفن',
                'verbose_name_plural': 'مجوز دفن',
            },
        ),
        migrations.AddField(
            model_name='deceased',
            name='presenter_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Presenter', verbose_name='معرف '),
        ),
        migrations.CreateModel(
            name='Death_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor_first_name', models.CharField(max_length=64, verbose_name='نام پزشک ')),
                ('doctor_last_name', models.CharField(max_length=64, verbose_name='نام خانوادگی پزشک ')),
                ('medical_system_number', models.CharField(max_length=32, verbose_name='شماره نظام پزشکی ')),
                ('death_certificate_number', models.CharField(max_length=32, verbose_name='شماره گواهی فوت ')),
                ('cause_death', models.CharField(max_length=64, verbose_name='علت فوت ')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='تاریخ فوت ')),
                ('status', models.CharField(choices=[('Accepted', 'تایید شده'), ('UnAccepted', 'در انتظار تایید')], default='UnAccepted', max_length=32, verbose_name='تاییدیه ')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='site_panel.Deceased', unique=True, verbose_name='متوفی ')),
            ],
            options={
                'verbose_name': 'گواهی فوت',
                'verbose_name_plural': 'گواهی فوت',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='عنوان ')),
                ('price', models.CharField(max_length=8, verbose_name='هزینه ')),
                ('after_death_service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.After_Death_Service', verbose_name='خدمات پس از مرگ مربوطه ')),
                ('deceased_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی ')),
                ('memorial_service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Memorial_Service', verbose_name='جلسه مربوطه ')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Place_Service', verbose_name='قبر مربوطه ')),
                ('reader_service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Reader_Service', verbose_name='مداح مربوطه ')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='خرید توسط ')),
            ],
            options={
                'verbose_name': 'کلیه خریدها',
                'verbose_name_plural': 'کلیه خریدها',
            },
        ),
        migrations.AddField(
            model_name='after_death_service',
            name='deceased_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی '),
        ),
        migrations.AddField(
            model_name='after_death_service',
            name='option_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='option', to='site_panel.Option', verbose_name='امکانات '),
        ),
        migrations.AddField(
            model_name='after_death_service',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='سفارش دهنده '),
        ),
    ]
