# Generated by Django 2.2.4 on 2019-09-04 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Place', verbose_name='قبر مربوطه '),
        ),
    ]
