# Generated by Django 2.2.4 on 2019-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='floor',
            field=models.CharField(choices=[('OneFloor', 'طبقه یک'), ('TwoFloor', 'طبقه دو')], default='OneFloor', max_length=12, verbose_name='طبقه '),
        ),
    ]
