# Generated by Django 2.2.4 on 2019-09-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0002_auto_20190916_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='deceased_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='site_panel.Deceased', verbose_name='متوفی '),
        ),
    ]
