# Generated by Django 2.2.4 on 2019-09-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0002_auto_20190904_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='place_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Place', verbose_name='قبر مربوطه '),
            preserve_default=False,
        ),
    ]
