# Generated by Django 2.2.4 on 2019-09-05 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0004_auto_20190905_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='presenter_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Presenter', verbose_name='معرف '),
        ),
        migrations.AlterField(
            model_name='license',
            name='place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Place', verbose_name='قبر مربوطه '),
        ),
    ]
