# Generated by Django 2.2.4 on 2019-09-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0004_auto_20190917_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='move_status',
            field=models.CharField(choices=[('SEND-OUT', 'اعزامی'), ('FERDOS-REZA', 'فردوس رضا')], default='FERDOS-REZA', max_length=32, verbose_name='وضعیت انتقال '),
        ),
        migrations.AlterField(
            model_name='license',
            name='place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to='site_panel.Place', verbose_name='قبر مربوطه '),
        ),
    ]
