# Generated by Django 2.2.4 on 2019-09-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0005_auto_20190905_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='place_id',
        ),
    ]
