# Generated by Django 2.2.4 on 2019-09-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0005_auto_20190917_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='first_name',
        ),
    ]
