# Generated by Django 2.2.4 on 2019-09-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0006_auto_20190917_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=8, null=True, verbose_name='قیمت '),
        ),
    ]
