# Generated by Django 2.2.4 on 2019-09-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0006_remove_deceased_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='deceased',
            name='last_name',
        ),
        migrations.AddField(
            model_name='deceased',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='نام و نام خانوادگی '),
            preserve_default=False,
        ),
    ]
