# Generated by Django 2.2.4 on 2019-09-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0007_auto_20190907_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='date_of_death',
        ),
    ]
