# Generated by Django 2.2.4 on 2019-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0007_auto_20190917_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهرهای اعزامی', 'verbose_name_plural': 'شهرهای اعزامی'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, verbose_name='اسم شهر '),
        ),
    ]
