# Generated by Django 2.2.4 on 2019-09-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0008_auto_20190919_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='deceased_status',
            field=models.CharField(choices=[('One', 'one'), ('Two', 'two')], default='_', max_length=32, verbose_name='وضعیت جنازه '),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='deceased_type',
            field=models.CharField(choices=[('One', 'one'), ('Two', 'two')], default='_', max_length=32, verbose_name='نوع جنازه '),
        ),
    ]
