# Generated by Django 2.2.4 on 2019-09-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0008_remove_deceased_date_of_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenter',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='presenter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='نام و نام خانوادگی '),
        ),
    ]
