# Generated by Django 2.2.4 on 2019-09-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0009_auto_20190919_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ghete',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='قطعه '),
        ),
    ]
