# Generated by Django 2.2.4 on 2019-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0009_auto_20190907_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='کد قبر '),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('ghete', 'radif', 'block', 'number', 'floor'), ('code', 'ghete', 'radif', 'block', 'number', 'floor')},
        ),
    ]
