# Generated by Django 2.2.4 on 2019-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0010_auto_20190919_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_service',
            name='document',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='شماره سند '),
        ),
    ]
