# Generated by Django 2.2.5 on 2019-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0011_auto_20190919_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(max_length=255, unique=True, verbose_name='طول جغرافیایی '),
        ),
    ]
