# Generated by Django 2.2.4 on 2019-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0011_auto_20190908_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenter',
            name='name',
        ),
        migrations.AddField(
            model_name='presenter',
            name='first_name',
            field=models.CharField(default='first_name', max_length=64, verbose_name='نام '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenter',
            name='last_name',
            field=models.CharField(default='first_name', max_length=64, verbose_name='نام خانوادگی '),
            preserve_default=False,
        ),
    ]
