# Generated by Django 2.2.5 on 2019-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0012_auto_20190920_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(max_length=255, verbose_name='طول جغرافیایی '),
        ),
    ]
