# Generated by Django 2.2.4 on 2019-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0012_auto_20190908_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='death_certificate',
            old_name='doctor_name',
            new_name='doctor_first_name',
        ),
        migrations.AddField(
            model_name='death_certificate',
            name='doctor_last_name',
            field=models.CharField(default=1, max_length=64, verbose_name='نام خانوادگی پزشک '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presenter',
            name='document',
            field=models.ImageField(default=1, upload_to='presenters-pic/'),
            preserve_default=False,
        ),
    ]
