# Generated by Django 2.2.4 on 2019-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0013_auto_20190913_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='status',
        ),
        migrations.AddField(
            model_name='license',
            name='license_status',
            field=models.CharField(choices=[('WAITING', 'درحال بررسی'), ('CONFIRMED', 'تایید شده')], default='WAITING', max_length=32, verbose_name='وضعیت مجوز '),
        ),
        migrations.AddField(
            model_name='license',
            name='move_status',
            field=models.CharField(choices=[('SEND-OUT', 'اعزامی'), ('FERDOS-REZA', 'باغ فردوس')], default='FERDOS-REZA', max_length=32),
        ),
    ]
