# Generated by Django 2.2.4 on 2019-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0015_auto_20190914_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='move_status',
            field=models.CharField(choices=[('SEND-OUT', 'اعزامی'), ('FERDOS-REZA', 'باغ فردوس')], default='FERDOS-REZA', max_length=32, verbose_name='وضعیت انتقال '),
        ),
    ]
