# Generated by Django 2.2.4 on 2019-09-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0015_auto_20190923_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='license', to='site_panel.Place', verbose_name='قبر مربوطه '),
        ),
    ]
