# Generated by Django 2.2.4 on 2019-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0016_auto_20190914_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='sex',
            field=models.CharField(choices=[('MALE', 'مرد'), ('FEMALE', 'زن'), ('UNKNOWN', 'ناشناخته')], default='UNKNOWN', max_length=32, verbose_name='جنسیت '),
        ),
    ]
