# Generated by Django 2.2.4 on 2019-09-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0017_auto_20190924_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='city_id',
        ),
        migrations.AddField(
            model_name='license',
            name='city_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='شهر اعزامی '),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
