# Generated by Django 2.2.4 on 2019-09-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0019_auto_20190924_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تماس '),
        ),
    ]
