# Generated by Django 2.2.4 on 2019-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0020_auto_20190924_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس معرف '),
        ),
    ]
