# Generated by Django 2.2.4 on 2019-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0021_presenter_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='license-pic/'),
        ),
    ]
