# Generated by Django 2.2.4 on 2019-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0022_auto_20191008_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='license-pic/'),
        ),
    ]
