# Generated by Django 2.2.4 on 2019-10-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0024_send_letter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Send_Letter',
            new_name='Archive',
        ),
    ]
