# Generated by Django 2.2.4 on 2019-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0025_auto_20191008_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='national_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره ملی '),
        ),
    ]
