# Generated by Django 2.2.4 on 2019-10-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0026_auto_20191008_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='slug',
        ),
    ]
