# Generated by Django 2.2.4 on 2019-10-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0027_remove_deceased_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_service',
            name='buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='خریدار '),
        ),
    ]
