# Generated by Django 2.2.4 on 2019-10-20 09:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0028_auto_20191008_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات '),
        ),
    ]
