# Generated by Django 2.2.4 on 2019-10-20 10:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0029_auto_20191020_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات '),
        ),
    ]
