# Generated by Django 2.2.4 on 2019-10-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0030_auto_20191020_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death_certificate',
            name='cause_death',
        ),
    ]
