# Generated by Django 2.2.4 on 2019-10-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0031_remove_death_certificate_cause_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause_Death',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='عنوان ')),
            ],
            options={
                'verbose_name': 'علت فوت',
                'verbose_name_plural': 'علت فوت',
            },
        ),
        migrations.AddField(
            model_name='death_certificate',
            name='cause_death_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Cause_Death', verbose_name='علت فوت '),
        ),
    ]
