# Generated by Django 2.2.4 on 2019-10-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0032_auto_20191022_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death_certificate',
            name='cause_death_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='site_panel.Cause_Death', verbose_name='علت فوت '),
        ),
    ]
