# Generated by Django 2.2.4 on 2019-10-30 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0034_auto_20191023_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='نام خدمات ')),
                ('price', models.CharField(max_length=8, verbose_name='هزینه ')),
            ],
        ),
        migrations.RemoveField(
            model_name='additional_service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='additional_service',
            name='price',
        ),
        migrations.AddField(
            model_name='additional_service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additional_service',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='additional_service',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Service_List', verbose_name='خدمات مربوطه '),
        ),
    ]
