# Generated by Django 2.2.4 on 2019-11-01 10:58

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0036_auto_20191030_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_service',
            name='buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, related_name='additional', to='site_panel.Buyer', verbose_name='خریدار '),
        ),
    ]
