# Generated by Django 2.2.4 on 2019-12-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0038_auto_20191130_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='deceased_type',
        ),
    ]
