# Generated by Django 2.2.4 on 2019-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0039_remove_deceased_deceased_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='deceased_type',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='شماره ثبت آرامستان '),
        ),
    ]
