# Generated by Django 2.2.4 on 2019-12-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0040_deceased_deceased_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='deceased_type',
        ),
        migrations.AddField(
            model_name='deceased',
            name='muni_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره ثبت آرامستان '),
        ),
    ]
