# Generated by Django 2.2.4 on 2019-12-17 10:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0041_auto_20191214_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='block',
            field=models.CharField(max_length=11, verbose_name='بلوک '),
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.CharField(max_length=11, verbose_name='شماره '),
        ),
        migrations.AlterField(
            model_name='place',
            name='radif',
            field=models.CharField(max_length=11, verbose_name='ردیف '),
        ),
        migrations.CreateModel(
            name='Movement_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmation', 'تایید'), ('disapproval', 'عدم تایید')], default='disapproval', max_length=32, verbose_name='وضعیت ')),
                ('license_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.License')),
            ],
        ),
    ]
