# Generated by Django 2.2.4 on 2019-12-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0043_auto_20191218_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_service',
            name='place_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place_service', to='site_panel.Place', verbose_name='قبر '),
        ),
    ]
