# Generated by Django 2.2.4 on 2019-12-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0046_auto_20191219_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_service',
            name='buyer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='site_panel.Buyer', verbose_name='خریدار '),
        ),
    ]
