# Generated by Django 2.2.4 on 2019-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0047_auto_20191222_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='license-pic/'),
        ),
        migrations.AddField(
            model_name='license',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='license-pic/'),
        ),
    ]
