# Generated by Django 2.2.4 on 2019-12-28 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0048_auto_20191227_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر '),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenter', to=settings.AUTH_USER_MODEL, verbose_name='کاربر '),
        ),
    ]
