# Generated by Django 2.2.4 on 2019-12-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0049_auto_20191228_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='document',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
