# Generated by Django 2.2.4 on 2019-12-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0052_auto_20191229_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='factor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='site_panel.Factor'),
        ),
    ]
