# Generated by Django 2.2.4 on 2019-12-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0054_auto_20191231_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='document',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
