# Generated by Django 2.2.4 on 2020-01-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0056_driver_driver_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_movement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver_movement',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
