# Generated by Django 2.2.4 on 2020-01-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0057_auto_20200102_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_movement',
            name='deceased_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased'),
        ),
    ]
