# Generated by Django 2.2.4 on 2020-01-02 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0058_driver_movement_deceased_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'راننده', 'verbose_name_plural': 'راننده'},
        ),
        migrations.AlterModelOptions(
            name='driver_movement',
            options={'verbose_name': 'انتقال متوفی', 'verbose_name_plural': 'انتقال متوفی'},
        ),
        migrations.AlterModelOptions(
            name='movement_certificate',
            options={'verbose_name': 'مجوز حمل', 'verbose_name_plural': 'مجوز حمل'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='national_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره ملی '),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس '),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر مقصد '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='deceased_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی مربوطه '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Driver', verbose_name='راننده مربوطه '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='هزینه '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع '),
        ),
        migrations.AlterField(
            model_name='driver_movement',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معرف '),
        ),
    ]
