# Generated by Django 2.2.4 on 2020-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0059_auto_20200102_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام '),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی '),
        ),
    ]
