# Generated by Django 2.2.4 on 2020-01-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0060_auto_20200102_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه '),
        ),
    ]
