# Generated by Django 2.2.4 on 2020-01-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0061_auto_20200107_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement_certificate',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر مقصد '),
        ),
        migrations.AddField(
            model_name='movement_certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات '),
        ),
        migrations.AddField(
            model_name='movement_certificate',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Driver', verbose_name='راننده مربوطه '),
        ),
        migrations.AddField(
            model_name='movement_certificate',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='هزینه '),
        ),
        migrations.AddField(
            model_name='movement_certificate',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع '),
        ),
        migrations.AddField(
            model_name='movement_certificate',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع '),
        ),
        migrations.DeleteModel(
            name='Driver_Movement',
        ),
    ]
