# Generated by Django 2.2.4 on 2020-01-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0062_auto_20200107_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement_certificate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='movement_certificate',
            name='price',
        ),
        migrations.RemoveField(
            model_name='movement_certificate',
            name='text',
        ),
        migrations.AddField(
            model_name='movement_certificate',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Service_List', verbose_name='شهر مقصد '),
        ),
    ]
