# Generated by Django 2.2.4 on 2020-01-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0064_auto_20200107_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PAID', 'پرداخت شده'), ('NOT PAID', 'پرداخت نشده')], default='NOT PAID', max_length=32, verbose_name='وضعیت پرداخت ')),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_service', to='site_panel.Car', verbose_name='ماشین مربوطه ')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی ')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Driver', verbose_name='راننده ')),
                ('target_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Target', verbose_name='مقصد مربوطه ')),
            ],
            options={
                'verbose_name': 'حمل متوفی',
                'verbose_name_plural': 'حمل متوفی',
            },
        ),
        migrations.CreateModel(
            name='Movement_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('confirmation', 'تایید'), ('disapproval', 'عدم تایید')], default='disapproval', max_length=32, verbose_name='وضعیت ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='زمان شروع ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Car', verbose_name='ماشین مورد نظر ')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Driver', verbose_name='راننده مربوطه ')),
                ('license_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.License')),
            ],
            options={
                'verbose_name': 'مجوز حمل',
                'verbose_name_plural': 'مجوز حمل',
            },
        ),
    ]
