# Generated by Django 2.2.4 on 2020-01-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0065_movement_certificate_movement_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement_service',
            name='price',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='قیمت '),
        ),
        migrations.AddField(
            model_name='movement_service',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع '),
        ),
        migrations.AddField(
            model_name='movement_service',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع '),
        ),
    ]
