# Generated by Django 2.2.4 on 2020-01-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0066_auto_20200112_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'مقصد حمل و نقل', 'verbose_name_plural': 'مقصد حمل و نقل'},
        ),
        migrations.DeleteModel(
            name='Movement_Certificate',
        ),
    ]
