# Generated by Django 2.2.4 on 2020-01-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0068_auto_20200112_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement_service',
            name='buyer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Buyer', verbose_name='معرف '),
            preserve_default=False,
        ),
    ]
