# Generated by Django 2.2.4 on 2020-01-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0069_movement_service_buyer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='movement_service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Movement_Service', verbose_name='حمل و نقل مربوطه '),
        ),
    ]
