# Generated by Django 2.2.4 on 2020-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0070_bill_movement_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PAID', 'پرداخت شده'), ('NOT PAID', 'پرداخت نشده')], default='NOT PAID', max_length=64, verbose_name='وضعیت پرداخت '),
        ),
    ]
