# Generated by Django 2.2.4 on 2020-01-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0071_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
