# Generated by Django 2.2.4 on 2020-01-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0072_bill_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='راننده '),
        ),
    ]
