# Generated by Django 2.2.4 on 2020-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0073_driver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='کد راننده '),
        ),
    ]
