# Generated by Django 2.2.4 on 2020-01-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0074_auto_20200113_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='movement_service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='site_panel.Movement_Service', verbose_name='حمل و نقل مربوطه '),
        ),
    ]
