# Generated by Django 2.2.4 on 2020-01-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0075_auto_20200113_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='death_certificate',
            name='place',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='محل فوت '),
        ),
    ]
