# Generated by Django 2.2.4 on 2020-01-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0076_death_certificate_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='توضیحات ')),
                ('picture', models.ImageField(upload_to='documents/', verbose_name='تصویر ')),
                ('deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی مربوطه ')),
            ],
            options={
                'verbose_name': 'اسناد',
                'verbose_name_plural': 'اسناد',
            },
        ),
    ]
