# Generated by Django 2.2.4 on 2020-01-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0077_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='کد '),
        ),
    ]
