# Generated by Django 2.2.4 on 2020-01-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0078_auto_20200115_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deceased_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_panel.Deceased', verbose_name='متوفی مربوطه '),
        ),
    ]
