# Generated by Django 2.2.4 on 2020-01-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_panel', '0079_auto_20200116_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='license',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='license',
            name='picture3',
        ),
    ]
